font_size 14.0
enable_audio_bell no
command_on_bell pw-play --volume 0.56 ~/.config/kitty/gawr-gura-a-short.mp3

# window settings: always same size on startup
remember_window_size  no
initial_window_width  105c
initial_window_height 35c

# Linux-specific clipboard behaviors:
# copy on selection, automatically cancel selection if either clipboard changed or explicitly `<C-S-c>`
copy_on_select                    yes
clear_selection_on_clipboard_loss no
map ctrl+shift+c                  clear_selection


# BEGIN_KITTY_FONTS
font_family      family="IosevkaTerm Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS


# BEGIN_KITTY_THEME
# Spring
include current-theme.conf
# END_KITTY_THEME