# https://wiki.archlinux.org/title/KMSCON
# Use `KMSCON` instead of `getty`
# ```
# ln -s '/usr/lib/systemd/system/kmsconvt@.service' '/etc/systemd/system/autovt@.service'
# ```

font-size=24
font-name=IosevkaTerm Nerd Font Mono
font-dpi=112

xkb-repeat-delay=252
xkb-repeat-rate=53
sb-size=1048575
palette=soft-black
