permit setenv {PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin} :wheel
permit nopass :plugdev as root cmd smartctl args -a /dev/nvme0n1
permit nopass :plugdev as root cmd smartctl args -a /dev/nvme1n1
permit nopass :plugdev as root cmd smartctl args -a /dev/sda
permit nopass :plugdev as root cmd lvs args -a -o +devices,name,cache_mode,cache_read_hits,cache_read_misses,cache_write_hits,cache_write_misses,cache_dirty_blocks,data_percent
